module.exports = {
  someSidebar: {
    'Standard Notes Docs': ['welcome'],
    Usage: [
      'usage',
      'usage/bold-editor',
      'usage/markdown-basic',
      'usage/markdown-math',
      'usage/markdown-pro',
      'usage/task-editor',
    ],
    FileSafe: ['filesafe/aws'],
    Listed: [
      'listed/about',
      'listed/register',
      'listed/publish',
      'listed/settings',
      'listed/subscribers',
      'listed/guestbook',
      'listed/styles',
      'listed/options',
    ],
    'Self Hosting': [
      'self-hosting/getting-started',
      'self-hosting/ec2-nginx',
      'self-hosting/docker',
      'self-hosting/heroku',
      'self-hosting/managing-options',
      'self-hosting/https-support',
    ],
    Extensions: [
      'extensions/intro',
      'extensions/building-an-extension',
      'extensions/local-setup',
      'extensions/themes',
      'extensions/actions',
      'extensions/publishing',
    ],
    Specification: ['specification/encryption', 'specification/sync'],
    Contribute: ['contribute'],
    //Docusaurus: ['doc1', 'doc2', 'doc3'],
    //Features: ['mdx'],
  },
};
